package com.networkmonitorpro.network;

import android.Manifest;import android.content.*;import android.content.pm.PackageManager;import android.net.*;import android.os.*;import android.telephony.*;import androidx.core.content.ContextCompat;import androidx.lifecycle.MutableLiveData;import java.io.IOException;import java.net.*;import java.util.concurrent.*;

public class NetworkDetector { private final Context c; private final ConnectivityManager cm; private final TelephonyManager tm; private long lastRx=TrafficStats.getTotalRxBytes(), lastTx=TrafficStats.getTotalTxBytes(), lastTs=System.currentTimeMillis(); private int signal=0; public final MutableLiveData<NetworkSnapshot> snapshots=new MutableLiveData<>(); private final ScheduledExecutorService exec=Executors.newSingleThreadScheduledExecutor();
 public NetworkDetector(Context c){this.c=c.getApplicationContext(); cm=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE); tm=(TelephonyManager)c.getSystemService(Context.TELEPHONY_SERVICE);} public void start(){listenSignal(); cm.registerDefaultNetworkCallback(new ConnectivityManager.NetworkCallback(){public void onAvailable(Network n){sample();} public void onLost(Network n){sample();} public void onCapabilitiesChanged(Network n,NetworkCapabilities nc){sample();}}); exec.scheduleAtFixedRate(this::sample,0,2,TimeUnit.SECONDS);} public void stop(){exec.shutdownNow();}
 private void listenSignal(){ if(ContextCompat.checkSelfPermission(c, Manifest.permission.READ_PHONE_STATE)!=PackageManager.PERMISSION_GRANTED)return; if(Build.VERSION.SDK_INT>=31) tm.registerTelephonyCallback(c.getMainExecutor(), new TelephonyCallback.SignalStrengthsListener(){ public void onSignalStrengthsChanged(SignalStrength s){signal=s.getLevel()*25;}}); else tm.listen(new PhoneStateListener(){ public void onSignalStrengthsChanged(SignalStrength s){signal=s.getLevel()*25;}}, PhoneStateListener.LISTEN_SIGNAL_STRENGTHS); }
 public void sample(){ Network n=cm.getActiveNetwork(); NetworkCapabilities nc=n==null?null:cm.getNetworkCapabilities(n); long now=System.currentTimeMillis(), rx=TrafficStats.getTotalRxBytes(), tx=TrafficStats.getTotalTxBytes(); long dt=Math.max(1,now-lastTs); long down=(rx-lastRx)*8000/dt, up=(tx-lastTx)*8000/dt; lastRx=rx;lastTx=tx;lastTs=now; String type=type(nc); boolean reach=nc!=null&&nc.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED); if(!reach) reach=probe(); String carrier=tm.getNetworkOperatorName(); String sim=sim(); int q=Math.max(0,Math.min(100,(signal)+(reach?20:0)+(type.startsWith("5G")?20:type.contains("4G")?12:type.equals("WiFi")?15:0))); snapshots.postValue(new NetworkSnapshot(type,carrier==null?"Unknown":carrier,sim,signal,down,up,reach,q)); }
 private String type(NetworkCapabilities nc){ if(nc==null)return "No Internet"; if(nc.hasTransport(NetworkCapabilities.TRANSPORT_WIFI))return "WiFi"; if(nc.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET))return "Ethernet"; if(nc.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)){ int nt=tm.getDataNetworkType(); if(nt==TelephonyManager.NETWORK_TYPE_NR) return Build.VERSION.SDK_INT>=30 && tm.getNetworkType()==TelephonyManager.NETWORK_TYPE_NR?"5G SA":"5G NSA"; if(nt==TelephonyManager.NETWORK_TYPE_LTE||nt==TelephonyManager.NETWORK_TYPE_IWLAN){ return signal>75?"4G+":"4G LTE";} if(nt==TelephonyManager.NETWORK_TYPE_UMTS||nt==TelephonyManager.NETWORK_TYPE_HSPA||nt==TelephonyManager.NETWORK_TYPE_HSDPA||nt==TelephonyManager.NETWORK_TYPE_HSUPA)return "3G"; return "2G";} return "No Internet"; }
 private String sim(){ switch(tm.getSimState()){case TelephonyManager.SIM_STATE_READY:return "Ready";case TelephonyManager.SIM_STATE_ABSENT:return "Absent";case TelephonyManager.SIM_STATE_PIN_REQUIRED:return "PIN required";default:return "Unknown";} }
 private boolean probe(){ try{HttpURLConnection h=(HttpURLConnection)new URL("https://clients3.google.com/generate_204").openConnection(); h.setConnectTimeout(1200); h.setReadTimeout(1200); h.connect(); return h.getResponseCode()==204;}catch(IOException e){return false;} }
}
